version: "3.8"

services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    shm_size: 5g
    environment:
      - SE_NODE_MAX_INSTANCES=10
      - SE_NODE_MAX_SESSIONS=10
    networks:
      - selenium-network
    container_name: selenium

  testrunner:
    build: ./Dockerfile
    volumes:
      - ./app:/app
    networks:
      - selenium-network
    depends_on:
      - selenium
    command: ["bash", "-c", "sleep 10 && docker run --rm -it --network container:selenium testrunner"]

networks:
  selenium-network:
